louvre_booking_homepage:
    path:     /
    defaults: { _controller: LouvreBookingBundle:Booking:home }

louvre_booking_forget:
    path:     /billet-perdu
    defaults: { _controller: LouvreBookingBundle:Booking:forget }

louvre_booking_ticket:
    path:     /reservation
    defaults: { _controller: LouvreBookingBundle:Booking:ticket }

louvre_booking_checkout:
    path:     /payement
    defaults: { _controller: LouvreBookingBundle:Booking:checkout }
